### ISSUE TITLE
Using without transpiler

### ISSUE THREAD

**Issue by dcversus** [pixely/details-polyfill#2]
If i connect script from 
/details-polyfill-es6/dist/details-polyfill.js
directly to head

i get error in browser
Uncaught ReferenceError: exports is not defined
    at details-polyfill.js:3

Please help. We need use this script on site without transpiler.

**Comment by pixely** [comment]
Thanks @dcversus, this issue is fixed in PR #3. Once I've had a chance to give this a test I'll merge it in and then you'll be able to reference the script directly in the head 😄

**Comment by dcversus** [comment]
thanks!
